const SPRINT8_VERSION = "v0.9.0-alpha1";

function getSprint8Settings() {
  return window.gptPlantWalkSettings || {
    companyName: "",
    plantName: "",
    companyLogo: "",
    sequenceStart: 1,
    sequenceDigits: 3,
    workOrderFormat: "WO-{DATE}-{SEQ}"
  };
}

function getSprint8WalkDate(walk) {
  const parsed = new Date(walk.startedAt);
  return Number.isNaN(parsed.getTime()) ? new Date() : parsed;
}

function getSprint8WorkOrderNumber(walk, issueIndex) {
  const settings = getSprint8Settings();
  const sequence = (Number(settings.sequenceStart) || 1) + issueIndex;
  if (typeof window.generateWorkOrderNumber === "function") {
    return window.generateWorkOrderNumber(sequence, getSprint8WalkDate(walk), settings);
  }
  return `WO-${String(sequence).padStart(Number(settings.sequenceDigits) || 3, "0")}`;
}

function buildSprint8Brand(settings) {
  const logo = settings.companyLogo
    ? `<img class="wo-company-logo" src="${settings.companyLogo}" alt="Company logo" />`
    : "";
  const company = settings.companyName ? `<strong>${escapeHtml(settings.companyName)}</strong>` : "";
  const plant = settings.plantName ? `<span>${escapeHtml(settings.plantName)}</span>` : "";
  return `<div class="wo-brand">${logo}<div>${company}${plant}</div></div>`;
}

function buildSprint8Photo(issue) {
  if (!issue.photos || issue.photos.length === 0) return "";
  return `<div class="wo-photo-wrap"><img class="wo-photo" src="${issue.photos[0]}" alt="Issue photo" /></div>`;
}

function buildSprint8WorkOrderPage(walk, issue, issueIndex) {
  const settings = getSprint8Settings();
  const number = getSprint8WorkOrderNumber(walk, issueIndex);
  const observation = issue.observation || "Photo-only issue";
  const photo = buildSprint8Photo(issue);

  return `
    <section class="work-order-page">
      <div class="wo-title-row">
        ${buildSprint8Brand(settings)}
        <div class="wo-document-title">
          <span>MAINTENANCE</span>
          <h2>Work Order</h2>
        </div>
      </div>

      <div class="wo-header-card">
        <div><span>WORK ORDER</span><strong>${escapeHtml(number)}</strong></div>
        <div><span>STATUS</span><strong>Open</strong></div>
        <div><span>PRIORITY</span><strong>AI to assign</strong></div>
        <div><span>TRADE</span><strong>AI to assign</strong></div>
        <div><span>AREA / EQUIPMENT</span><strong>AI to assign</strong></div>
        <div><span>REPORTED</span><strong>${escapeHtml(issue.time)}</strong></div>
      </div>

      <div class="wo-content-grid ${photo ? "has-photo" : ""}">
        <div class="wo-section wo-observation">
          <h3>Initial Observation</h3>
          <p>${escapeHtml(observation)}</p>
        </div>
        ${photo}
      </div>

      <div class="wo-section wo-actions">
        <h3>Suggested Corrective Actions</h3>
        <p class="wo-planner-note">Complete from the AI maintenance report before issuing to the technician.</p>
        <div class="wo-check-line">☐ Verify the reported condition and identify the failure source.</div>
        <div class="wo-check-line">☐ Complete the approved corrective repair.</div>
        <div class="wo-check-line">☐ Test the equipment and confirm normal operation.</div>
      </div>

      <div class="wo-section wo-notes">
        <h3>Technician — Work Performed / Findings</h3>
        <div class="wo-writing-lines"><i></i><i></i><i></i><i></i></div>
      </div>

      <div class="wo-section wo-parts">
        <h3>Parts Used</h3>
        <table>
          <thead><tr><th>Part Number</th><th>Description</th><th>Qty</th></tr></thead>
          <tbody><tr><td></td><td></td><td></td></tr><tr><td></td><td></td><td></td></tr></tbody>
        </table>
      </div>

      <div class="wo-section wo-completion">
        <h3>Completion / Sign-Off</h3>
        <div class="wo-signoff-grid">
          <div><span>COMPLETED BY</span><strong>________________________</strong></div>
          <div><span>DATE</span><strong>____________</strong></div>
          <div><span>TIME</span><strong>__________</strong></div>
          <div><span>COMPLETE</span><strong>☐ Yes</strong></div>
        </div>
      </div>

      <p class="wo-footer">Generated by GPT Plant Walk • Work Order Standard v1.0 • ${escapeHtml(number)}</p>
    </section>`;
}

const sprint8OriginalProfessionalReport = window.buildProfessionalReportHtml;
window.buildProfessionalReportHtml = function buildProfessionalReportHtmlSprint8(walk) {
  const base = typeof sprint8OriginalProfessionalReport === "function"
    ? sprint8OriginalProfessionalReport(walk)
    : "";
  const pages = walk.issues.map((issue, index) => buildSprint8WorkOrderPage(walk, issue, index)).join("");
  return `${base}<section class="work-order-packet-heading"><h2>Printable Work Orders</h2><p>One Work Order Standard v1.0 page is provided for each recorded issue.</p></section>${pages}`;
};

const sprint8OriginalPrompt = window.buildChatGptReport;
window.buildChatGptReport = function buildChatGptReportSprint8(walk) {
  let prompt = typeof sprint8OriginalPrompt === "function" ? sprint8OriginalPrompt(walk) : "";
  prompt = prompt.replace(
    "6. Issue Details With Original Notes",
    `6. Issue Details With Original Notes\n\n7. Completed Work Order Data\nFor each issue, provide final values for Priority, Area / Equipment, Trade, Problem, Recommended Repair, Materials / Parts, Verification, and Confidence. Use the exact Suggested WO # supplied for that issue so the data matches the printable Work Order Standard v1.0 page in the attached PDF.`
  );
  return prompt;
};

function applySprint8Version() {
  const footer = document.getElementById("appVersionText");
  if (footer) footer.textContent = `GPT Plant Walk ${SPRINT8_VERSION} — Sprint 8 Alpha 1`;
  try {
    if (typeof activeWalk !== "undefined" && activeWalk) activeWalk.version = SPRINT8_VERSION;
  } catch (error) {
    console.error("Could not apply Sprint 8 version.", error);
  }
}

const sprint8StartButton = document.getElementById("startWalkBtn");
if (sprint8StartButton) sprint8StartButton.addEventListener("click", () => window.setTimeout(applySprint8Version, 0));
window.setTimeout(applySprint8Version, 250);
